# Generated by Django 4.0.6 on 2022-11-04 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ForeignKey(db_column='Avatar', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_avatar', to='accounts.useravatar'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
