# Generated by Django 4.0.6 on 2022-09-21 13:35

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_avatar_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('avatar', models.FileField(blank=True,
                                            upload_to=accounts.models.user_avatar,
                                            verbose_name='Avatar')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='accounts.multiavatar'),
            preserve_default=False,
        ),
    ]
