# Generated by Django 4.0.6 on 2022-09-12 11:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='anonymous.png', upload_to=accounts.models.user_avatar),
        ),
    ]
