# Generated by Django 4.0.6 on 2022-09-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_multiavatar_user_id_alter_user_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiavatar',
            name='user_id',
        ),
    ]
