# Generated by Django 4.0.6 on 2022-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiavatar',
            name='avatar',
            field=models.FileField(blank=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
