# Generated by Django 4.0.6 on 2022-09-21 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_multiavatar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiavatar',
            name='user_id',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
