# Generated by Django 4.0.6 on 2022-09-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_multiavatar_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiAvatar',
            new_name='UserAvatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_avatar',
        ),
    ]
