# Generated by Django 4.0.6 on 2022-09-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_avatar_userid_alter_useravatar_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserId',
        ),
    ]
