# Generated by Django 4.0.6 on 2022-09-21 18:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_useravatar_user_id_delete_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='anonymous.png', upload_to=accounts.models.user_avatar),
        ),
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
