# Generated by Django 4.0.6 on 2022-09-21 18:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_avatar_delete_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to=accounts.models.user_avatar),
        ),
    ]
