# Generated by Django 4.0.6 on 2022-09-23 14:50

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_avatar', models.FileField(blank=True, upload_to=accounts.models.user_avatar)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='accounts.useravatar'),
            preserve_default=False,
        ),
    ]
