# Generated by Django 4.0.6 on 2022-09-23 14:52

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_useravatar_remove_user_avatar_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='accounts.useravatar'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='u_avatar',
            field=models.FileField(blank=True,
                                   null=True,
                                   upload_to=accounts.models.user_avatar),
        ),
    ]
