# Generated by Django 4.0.6 on 2022-09-23 17:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_user_avatar_alter_useravatar_u_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='u_avatar',
            field=models.FileField(upload_to=accounts.models.user_avatar),
        ),
    ]
