# Generated by Django 4.0.6 on 2022-09-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_user_avatar_alter_useravatar_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='u_id',
            field=models.IntegerField(),
        ),
    ]
