# Generated by Django 4.0.6 on 2022-09-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='u_id',
            field=models.IntegerField(null=True),
        ),
    ]
