# Generated by Django 4.0.6 on 2022-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_useravatar_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='u_id',
            field=models.IntegerField(),
        ),
    ]
