# Generated by Django 4.0.6 on 2022-09-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_useravatar_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ForeignKey(db_column='u_id',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='accounts.useravatar'),
        ),
    ]
