# Generated by Django 4.0.6 on 2022-09-25 21:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_useravatar_u_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='u_avatar',
            field=models.FileField(default='icons/anonymous.png', upload_to=accounts.models.user_avatar),
        ),
    ]
