version: "3"

services:
  backend:
    image: local:0.0.1
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/app/build"
    env_file:
      - "./.env"
    build: .
    ports:
      - "8000:8000"

  celery:
    image: local:0.0.1
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: celery -A settings worker --loglevel=INFO --pidfile=/tmp/celery.pid

  celerybeat:
    image: local:0.0.1
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: celery -A settings beat --loglevel=INFO --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid

  celeryflower:
    image: local:0.0.1
    build: .
    container_name: celeryflower
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: celery -A settings flower --address=0.0.0.0 --port=5555
#    command: celery -A settings flower --broker=amqp://guest:guest@localhost:5566//


  memcached:
    image: memcached:1.6.17
    container_name: memcached
    env_file:
      - .env
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.11.2-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"

  nginx:
    image: nginx:latest
#    build:localnginx:0.0.1
#      dockerfile: dockerfile.nginx
#      context: .
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./default:/etc/nginx/conf.d/default.conf"

volumes:
  data: {}