# Generated by Django 4.0.6 on 2022-11-04 19:19

import currency.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(default='testemail@gmail.com', max_length=60)),
                ('email_to', models.EmailField(max_length=60)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=7000)),
                ('sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ContactUs',
            },
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.FloatField()),
                ('request_method', models.CharField(max_length=4)),
                ('query_params', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=122)),
            ],
            options={
                'verbose_name_plural': 'ResponseLog',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('code_name', models.CharField(max_length=20, unique=True)),
                ('bank_avatar', models.FileField(blank=True, upload_to=currency.models.bank_avatar)),
            ],
            options={
                'verbose_name_plural': 'Source',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency_type', models.CharField(choices=[('UAH', 'Hrivna'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('BTC', 'Bitcoin')], default='UAH', max_length=3)),
                ('currency_type', models.CharField(choices=[('UAH', 'Hrivna'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('BTC', 'Bitcoin')], default='USD', max_length=3)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.source')),
            ],
            options={
                'verbose_name_plural': 'Rate',
            },
        ),
    ]
