# Generated by Django 4.0.6 on 2022-07-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=64)),
                ('theme', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
    ]
