# Generated by Django 4.0.6 on 2022-09-16 20:13

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_contactus_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='bank_avatar',
            field=models.FileField(blank=True, upload_to=currency.models.bank_avatar),
        ),
    ]
