version: "3"

services:
  backend:
    image: local:0.0.1
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/app/build"
    env_file:
      - "./.env"
    build: .
    ports:
      - "8000:8000"


  postgres:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"


volumes:
  data: {}